name: 'Jira - Track Build Projects'
description: 'Find projects in Github Organization by Jira Project Key and track them'
inputs:
  github_token:
    description: 'Github Token'
    required: true
  commit_sha:
    description: 'Github commit sha'
    required: true
  workflow_id:
    description: 'Github workflow name'
    required: false
  actual_repository:
    description: 'Github repository name'
    required: true
  trigger_workflow:
    description: 'Trigger workflow'
    required: true
outputs:
  message:
    description: 'The output message'
runs:
  using: node20
  main: dist/index.js
  post: dist/index.js